# Generated by Django 4.2.2 on 2023-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_released', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('War', 'War'), ('Adventure', 'Adventure'), ('Documentary', 'Documentary'), ('Romance', 'Romance'), ('Animation', 'Animation'), ('Drama', 'Drama'), ('Science fiction', 'Scence fiction'), ('Sports', 'Sports'), ('Musical', 'Musical'), ('Thriller', 'Thriller'), ('Horror', 'Horror')], max_length=20)),
                ('actors', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('poster', models.ImageField(upload_to='movie_posters/')),
                ('trailer_link', models.URLField()),
            ],
        ),
    ]
