# Generated by Django 4.2.2 on 2023-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_remove_movie_actors_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(default=True),
        ),
    ]
