# Generated by Django 4.2.2 on 2023-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_actor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
