# Generated by Django 4.2.2 on 2023-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0006_alter_actor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
